// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxW36RidRGXHxPeVJICFSDTJvtacGQDs',
    appId: '1:144583428047:web:14b442ca4fe006436834ba',
    messagingSenderId: '144583428047',
    projectId: 'flutter-location-app-2344c',
    authDomain: 'flutter-location-app-2344c.firebaseapp.com',
    storageBucket: 'flutter-location-app-2344c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGn4EQxMJ7jhiwlw8DCUtF_lPu2QueAo',
    appId: '1:144583428047:android:e54914450a975ed26834ba',
    messagingSenderId: '144583428047',
    projectId: 'flutter-location-app-2344c',
    storageBucket: 'flutter-location-app-2344c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDELaqy8xDwZPi1wi5OPCFD9SD6VSFLVhE',
    appId: '1:144583428047:ios:03884b684740f6f36834ba',
    messagingSenderId: '144583428047',
    projectId: 'flutter-location-app-2344c',
    storageBucket: 'flutter-location-app-2344c.firebasestorage.app',
    iosBundleId: 'com.example.flutterLocationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDELaqy8xDwZPi1wi5OPCFD9SD6VSFLVhE',
    appId: '1:144583428047:ios:03884b684740f6f36834ba',
    messagingSenderId: '144583428047',
    projectId: 'flutter-location-app-2344c',
    storageBucket: 'flutter-location-app-2344c.firebasestorage.app',
    iosBundleId: 'com.example.flutterLocationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQxW36RidRGXHxPeVJICFSDTJvtacGQDs',
    appId: '1:144583428047:web:684510f69e85b6df6834ba',
    messagingSenderId: '144583428047',
    projectId: 'flutter-location-app-2344c',
    authDomain: 'flutter-location-app-2344c.firebaseapp.com',
    storageBucket: 'flutter-location-app-2344c.firebasestorage.app',
  );
}
